@echo off
rem Auto-generated by five250 when "fre"'s variables were saved. Re-generated on every
rem save - hand edits here will be overwritten; edit the .data.csv instead, then re-save vars.
set "DIR=%~dp0"
java -jar "%DIR%..\..\five250.jar" run-suite --flow custom-steps --file fre --data-csv "%DIR%fre.data.csv"
exit /b %ERRORLEVEL%
