#!/usr/bin/env bash
# Auto-generated by five250 when "fre"'s variables were saved. Re-generated on every
# save - hand edits here will be overwritten; edit the .data.csv instead, then re-save vars.
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec java -jar "$DIR/../../five250.jar" run-suite --flow custom-steps --file fre --data-csv "$DIR/fre.data.csv"
