package com.acabes.five250;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Whenever a scenario's ${NAME} variables are saved, records that value set as one more row
 * of a "<file>.data.csv" (columns = every variable name ever saved, one row per save = one
 * data-driven run) and (re)writes a "<file>.bat" + "<file>.run.ps1" pair next to the scenario
 * that replays the whole suite once per row of that CSV, each time with that row's values.
 */
public final class DataDrivenRunner {

    private DataDrivenRunner() {}

    public static File dataFile(File flowDir, String fileName) {
        return new File(flowDir, fileName + ".data.csv");
    }

    public static File batFile(File flowDir, String fileName) {
        return new File(flowDir, fileName + ".bat");
    }

    public static File ps1File(File flowDir, String fileName) {
        return new File(flowDir, fileName + ".run.ps1");
    }

    /** Appends the given variable set as a new row, growing the column set as needed, and (re)writes the .bat/.ps1 pair. */
    public static void onVarsSaved(File flowDir, String flowName, String fileName, Map<String, String> vars) throws IOException {
        if (!vars.isEmpty()) {
            appendRow(dataFile(flowDir, fileName), vars);
        }
        writeRunner(flowDir, flowName, fileName);
    }

    private static void appendRow(File dataFile, Map<String, String> vars) throws IOException {
        List<Map<String, String>> existing = Csv.read(dataFile);
        Set<String> columns = new LinkedHashSet<>();
        for (Map<String, String> row : existing) columns.addAll(row.keySet());
        columns.addAll(vars.keySet());

        List<String> header = new ArrayList<>(columns);
        List<Map<String, String>> rows = new ArrayList<>(existing);
        rows.add(new LinkedHashMap<>(vars));
        Csv.write(dataFile, header, rows);
    }

    private static void writeRunner(File flowDir, String flowName, String fileName) throws IOException {
        File ps1 = ps1File(flowDir, fileName);
        File bat = batFile(flowDir, fileName);

        String ps1Content =
            "# Auto-generated by five250 when \"" + fileName + "\"'s variables were saved. Re-generated on every save -\n" +
            "# hand edits here will be overwritten; edit the .data.csv (or save vars again) instead.\n" +
            "$ErrorActionPreference = 'Stop'\n" +
            "$here = Split-Path -Parent $MyInvocation.MyCommand.Path\n" +
            "$jar = Join-Path $here '..\\..\\five250.jar'\n" +
            "$dataCsv = Join-Path $here '" + fileName + ".data.csv'\n" +
            "$rows = @(Import-Csv -Path $dataCsv)\n" +
            "if ($rows.Count -eq 0) { Write-Host 'No rows in " + fileName + ".data.csv - nothing to run.'; exit 0 }\n" +
            "$failed = 0\n" +
            "for ($i = 0; $i -lt $rows.Count; $i++) {\n" +
            "    $row = $rows[$i]\n" +
            "    $varArgs = @()\n" +
            "    foreach ($p in $row.PSObject.Properties) { $varArgs += '--var'; $varArgs += \"$($p.Name)=$($p.Value)\" }\n" +
            "    $allArgs = @('run-suite', '--flow', '" + flowName + "', '--file', '" + fileName + "') + $varArgs\n" +
            "    Write-Host \"==> row $($i + 1)/$($rows.Count): java -jar five250.jar $($allArgs -join ' ')\"\n" +
            "    & java -jar $jar @allArgs\n" +
            "    if ($LASTEXITCODE -ne 0) { $failed++ }\n" +
            "}\n" +
            "Write-Host ''\n" +
            "Write-Host \"$($rows.Count - $failed) / $($rows.Count) row(s) passed\"\n" +
            "exit ([int]($failed -gt 0))\n";

        String batContent =
            "@echo off\r\n" +
            "rem Auto-generated by five250 when \"" + fileName + "\"'s variables were saved. Re-generated on every\r\n" +
            "rem save - hand edits here will be overwritten; edit the .data.csv instead, then re-save vars.\r\n" +
            "powershell -NoProfile -ExecutionPolicy Bypass -File \"%~dp0" + fileName + ".run.ps1\"\r\n" +
            "exit /b %ERRORLEVEL%\r\n";

        Files.writeString(ps1.toPath(), ps1Content, StandardCharsets.UTF_8);
        Files.writeString(bat.toPath(), batContent, StandardCharsets.UTF_8);
    }
}
