package com.acabes.five250;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Whenever a scenario's ${NAME} variables are saved, records that value set as one more row
 * of a "<file>.data.csv" (columns = every variable name ever saved, one row per save = one
 * data-driven run) and (re)writes a "<file>.bat" (Windows) + "<file>.sh" (everything else) pair
 * next to the scenario. Both are trivial wrappers around `run-suite --data-csv`, which does the
 * actual per-row looping in Java (see Cli.runSuite) - reusing the same CSV parser (Csv.java) the
 * rest of five250 uses, instead of re-parsing CSV in batch/PowerShell/shell.
 */
public final class DataDrivenRunner {

    private DataDrivenRunner() {}

    public static File dataFile(File flowDir, String fileName) {
        return new File(flowDir, fileName + ".data.csv");
    }

    public static File batFile(File flowDir, String fileName) {
        return new File(flowDir, fileName + ".bat");
    }

    public static File shFile(File flowDir, String fileName) {
        return new File(flowDir, fileName + ".sh");
    }

    /** Appends the given variable set as a new row, growing the column set as needed, and (re)writes the .bat/.sh pair. */
    public static void onVarsSaved(File flowDir, String flowName, String fileName, Map<String, String> vars) throws IOException {
        if (!vars.isEmpty()) {
            appendRow(dataFile(flowDir, fileName), vars);
        }
        writeRunner(flowDir, flowName, fileName);
    }

    private static void appendRow(File dataFile, Map<String, String> vars) throws IOException {
        List<Map<String, String>> existing = Csv.read(dataFile);
        Set<String> columns = new LinkedHashSet<>();
        for (Map<String, String> row : existing) columns.addAll(row.keySet());
        columns.addAll(vars.keySet());

        List<String> header = new ArrayList<>(columns);
        List<Map<String, String>> rows = new ArrayList<>(existing);
        rows.add(new LinkedHashMap<>(vars));
        Csv.write(dataFile, header, rows);
    }

    private static void writeRunner(File flowDir, String flowName, String fileName) throws IOException {
        File bat = batFile(flowDir, fileName);
        File sh = shFile(flowDir, fileName);

        String batContent =
            "@echo off\r\n" +
            "rem Auto-generated by five250 when \"" + fileName + "\"'s variables were saved. Re-generated on every\r\n" +
            "rem save - hand edits here will be overwritten; edit the .data.csv instead, then re-save vars.\r\n" +
            "set \"DIR=%~dp0\"\r\n" +
            "java -jar \"%DIR%..\\..\\five250.jar\" run-suite --flow " + flowName + " --file " + fileName
                + " --data-csv \"%DIR%" + fileName + ".data.csv\"\r\n" +
            "exit /b %ERRORLEVEL%\r\n";

        String shContent =
            "#!/usr/bin/env bash\n" +
            "# Auto-generated by five250 when \"" + fileName + "\"'s variables were saved. Re-generated on every\n" +
            "# save - hand edits here will be overwritten; edit the .data.csv instead, then re-save vars.\n" +
            "DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\"\n" +
            "exec java -jar \"$DIR/../../five250.jar\" run-suite --flow " + flowName + " --file " + fileName
                + " --data-csv \"$DIR/" + fileName + ".data.csv\"\n";

        Files.writeString(bat.toPath(), batContent, StandardCharsets.UTF_8);
        Files.writeString(sh.toPath(), shContent, StandardCharsets.UTF_8);
        sh.setExecutable(true, false);
    }
}
