package com.acabes.five250;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Manages a scenario's "<file>.data.csv" (columns = variable names, one row per data-driven run)
 * and (re)writes a "<file>.bat" (Windows) + "<file>.sh" (everything else) pair next to the
 * scenario. Both are trivial wrappers around `run-suite --data-csv`, which does the actual
 * per-row looping in Java (see Cli.runSuite) - reusing the same CSV parser (Csv.java) the rest of
 * five250 uses, instead of re-parsing CSV in batch/PowerShell/shell.
 *
 * Two ways rows get into the grid: saveGrid() replaces it wholesale (the GUI's Variables panel
 * edits this grid directly - add/remove rows and columns, same shape as the file on disk), or
 * onVarsSaved()/appendRow() (kept for the older /api/scenario-vars name/value PUT) grows it by
 * exactly one row per save.
 */
public final class DataDrivenRunner {

    private DataDrivenRunner() {}

    public static File dataFile(File flowDir, String fileName) {
        return new File(flowDir, fileName + ".data.csv");
    }

    public static File batFile(File flowDir, String fileName) {
        return new File(flowDir, fileName + ".bat");
    }

    public static File shFile(File flowDir, String fileName) {
        return new File(flowDir, fileName + ".sh");
    }

    /** Appends the given variable set as a new row, growing the column set as needed, and (re)writes the .bat/.sh pair. */
    public static void onVarsSaved(File flowDir, String flowName, String fileName, Map<String, String> vars) throws IOException {
        if (!vars.isEmpty()) {
            appendRow(dataFile(flowDir, fileName), vars);
        }
        writeRunner(flowDir, flowName, fileName);
    }

    /**
     * Replaces the whole data-driven grid wholesale with what the engineer edited directly (the
     * GUI's Variables panel IS this grid now, not a separate name/value list) - unlike
     * onVarsSaved()/appendRow(), which only ever grow the file by one row. The LAST row becomes
     * the "current" single active variable set (written to <file>.vars.csv, in the name/value
     * shape Variables.load()/GenericStepFlow substitution already expect), so a plain Run All
     * keeps using "whatever I saved most recently" without the two files ever disagreeing.
     */
    public static void saveGrid(File flowDir, File varsFile, String flowName, String fileName,
                                 List<String> columns, List<Map<String, String>> rows) throws IOException {
        Csv.write(dataFile(flowDir, fileName), columns, rows);

        List<Map<String, String>> varsRows = new ArrayList<>();
        Map<String, String> current = rows.isEmpty() ? Map.of() : rows.get(rows.size() - 1);
        for (String col : columns) {
            Map<String, String> varRow = new LinkedHashMap<>();
            varRow.put("name", col);
            varRow.put("value", current.getOrDefault(col, ""));
            varsRows.add(varRow);
        }
        Variables.write(varsFile, varsRows);

        writeRunner(flowDir, flowName, fileName);
    }

    private static void appendRow(File dataFile, Map<String, String> vars) throws IOException {
        List<Map<String, String>> existing = Csv.read(dataFile);
        Set<String> columns = new LinkedHashSet<>();
        for (Map<String, String> row : existing) columns.addAll(row.keySet());
        columns.addAll(vars.keySet());

        List<String> header = new ArrayList<>(columns);
        List<Map<String, String>> rows = new ArrayList<>(existing);
        rows.add(new LinkedHashMap<>(vars));
        Csv.write(dataFile, header, rows);
    }

    private static void writeRunner(File flowDir, String flowName, String fileName) throws IOException {
        File bat = batFile(flowDir, fileName);
        File sh = shFile(flowDir, fileName);

        // Forwards whatever the caller passes on the command line straight through to run-suite,
        // instead of hard-coding --data-csv - so `variable-demo.bat --var CMD1=WRKSYSSTS` runs once
        // ad hoc with just that var (bypassing the saved grid entirely), while plain
        // `variable-demo.bat` (or an explicit --data-csv/--var-less invocation) keeps looping this
        // suite's own saved <file>.data.csv row-by-row, same as before this per-call override existed.
        String batContent =
            "@echo off\r\n" +
            "rem Auto-generated by five250 when \"" + fileName + "\"'s variables were saved. Re-generated on every\r\n" +
            "rem save - hand edits here will be overwritten; edit the .data.csv instead, then re-save vars.\r\n" +
            "rem Pass --var NAME=VALUE (repeatable) to run once with your own values instead of looping\r\n" +
            "rem the saved data-csv, or --data-csv <path> to loop a different csv than this suite's own.\r\n" +
            "setlocal\r\n" +
            "set \"DIR=%~dp0\"\r\n" +
            "set \"ARGS=%*\"\r\n" +
            "echo %ARGS% | findstr /C:\"--var\" /C:\"--data-csv\" >nul\r\n" +
            "if %ERRORLEVEL%==0 (\r\n" +
            "  java -jar \"%DIR%..\\..\\five250.jar\" run-suite --flow " + flowName + " --file " + fileName + " %*\r\n" +
            ") else (\r\n" +
            "  java -jar \"%DIR%..\\..\\five250.jar\" run-suite --flow " + flowName + " --file " + fileName
                + " --data-csv \"%DIR%" + fileName + ".data.csv\" %*\r\n" +
            ")\r\n" +
            "exit /b %ERRORLEVEL%\r\n";

        String shContent =
            "#!/usr/bin/env bash\n" +
            "# Auto-generated by five250 when \"" + fileName + "\"'s variables were saved. Re-generated on every\n" +
            "# save - hand edits here will be overwritten; edit the .data.csv instead, then re-save vars.\n" +
            "# Pass --var NAME=VALUE (repeatable) to run once with your own values instead of looping\n" +
            "# the saved data-csv, or --data-csv <path> to loop a different csv than this suite's own.\n" +
            "DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\"\n" +
            "if [[ \"$*\" == *\"--var\"* || \"$*\" == *\"--data-csv\"* ]]; then\n" +
            "  exec java -jar \"$DIR/../../five250.jar\" run-suite --flow " + flowName + " --file " + fileName + " \"$@\"\n" +
            "else\n" +
            "  exec java -jar \"$DIR/../../five250.jar\" run-suite --flow " + flowName + " --file " + fileName
                + " --data-csv \"$DIR/" + fileName + ".data.csv\" \"$@\"\n" +
            "fi\n";

        Files.writeString(bat.toPath(), batContent, StandardCharsets.UTF_8);
        Files.writeString(sh.toPath(), shContent, StandardCharsets.UTF_8);
        sh.setExecutable(true, false);
    }
}
