package com.acabes.five250;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;

/**
 * (Re)writes a "<name>.bat" (Windows) + "<name>.sh" (Linux/macOS) pair next to a script - the
 * scripts-tab equivalent of DataDrivenRunner's suite .bat/.sh pair, both trivial wrappers around a
 * CLI call so a script can be launched by double-click or from an external scheduler/CI job
 * without remembering the jar's own path. Unlike a suite's wrapper (which loops a saved
 * <file>.data.csv row-by-row by default), a script has no saved default variable set at all -
 * every "--var NAME=VALUE" is just forwarded straight through to "run-script <name>" untouched,
 * landing on the script's own read-only `args` global (see HttpApi.SCRIPT_DECLARATIONS' doc on
 * `args`).
 *
 * Embeds the ABSOLUTE path to this running jar (Home.file("five250.jar"), resolved once at
 * generation time) rather than a "../.." relative climb from the script's own directory - scripts
 * live flat under a project's own scripts/ folder (one level down), and that folder's depth below
 * the jar differs between the "default" project (project root == Home.DIR, the jar's own
 * directory) and any other project (project root == Home.DIR/projects/&lt;name&gt;) - a fixed
 * relative-path assumption would only be correct for one of those two cases. An absolute path
 * sidesteps that entirely, correct for every project.
 */
public final class ScriptBatchFiles {

    private ScriptBatchFiles() {}

    public static File batFile(File scriptsDir, String name) {
        return new File(scriptsDir, name + ".bat");
    }

    public static File shFile(File scriptsDir, String name) {
        return new File(scriptsDir, name + ".sh");
    }

    /** Writes both wrappers if either is missing - cheap self-heal for a script that predates this
     * feature, called on every scripts-list GET, in addition to the unconditional write on create. */
    public static void writeIfMissing(File scriptsDir, String name) throws IOException {
        if (!batFile(scriptsDir, name).exists() || !shFile(scriptsDir, name).exists()) {
            write(scriptsDir, name);
        }
    }

    public static void write(File scriptsDir, String name) throws IOException {
        String jarPathWin = Home.file("five250.jar").getAbsolutePath();
        String jarPathPosix = jarPathWin.replace('\\', '/');

        String batContent =
            "@echo off\r\n" +
            "rem Auto-generated by five250 for \"" + name + ".js\" - re-generated whenever this script is\r\n" +
            "rem (re)created, and self-healed on the next Scripts-tab load if missing. Hand edits here will\r\n" +
            "rem be overwritten - edit the script itself instead.\r\n" +
            "rem Pass --var NAME=VALUE (repeatable) through to the script's own read-only `args` global:\r\n" +
            "rem   " + name + ".bat --var HOST=pub400.com --var COMMAND=WRKACTJOB\r\n" +
            "java -jar \"" + jarPathWin + "\" run-script " + name + " %*\r\n" +
            "exit /b %ERRORLEVEL%\r\n";

        String shContent =
            "#!/usr/bin/env bash\n" +
            "# Auto-generated by five250 for \"" + name + ".js\" - re-generated whenever this script is\n" +
            "# (re)created, and self-healed on the next Scripts-tab load if missing. Hand edits here will\n" +
            "# be overwritten - edit the script itself instead.\n" +
            "# Pass --var NAME=VALUE (repeatable) through to the script's own read-only `args` global:\n" +
            "#   ./" + name + ".sh --var HOST=pub400.com --var COMMAND=WRKACTJOB\n" +
            "exec java -jar \"" + jarPathPosix + "\" run-script " + name + " \"$@\"\n";

        Files.writeString(batFile(scriptsDir, name).toPath(), batContent, StandardCharsets.UTF_8);
        File sh = shFile(scriptsDir, name);
        Files.writeString(sh.toPath(), shContent, StandardCharsets.UTF_8);
        sh.setExecutable(true, false);
    }

    public static void delete(File scriptsDir, String name) {
        batFile(scriptsDir, name).delete();
        shFile(scriptsDir, name).delete();
    }
}
