@echo off
rem Auto-generated by five250 for "cli-args-demo.js" - re-generated whenever this script is
rem (re)created, and self-healed on the next Scripts-tab load if missing. Hand edits here will
rem be overwritten - edit the script itself instead.
rem Pass --var NAME=VALUE (repeatable) through to the script's own read-only `args` global:
rem   cli-args-demo.bat --var HOST=pub400.com --var COMMAND=WRKACTJOB
java -jar "C:\acabes\as400\five250\five250.jar" run-script cli-args-demo %*
exit /b %ERRORLEVEL%
