#!/usr/bin/env bash
# Auto-generated by five250 for "js_orchestrator_demo.js" - re-generated whenever this script is
# (re)created, and self-healed on the next Scripts-tab load if missing. Hand edits here will
# be overwritten - edit the script itself instead.
# Pass --var NAME=VALUE (repeatable) through to the script's own read-only `args` global:
#   ./js_orchestrator_demo.sh --var HOST=pub400.com --var COMMAND=WRKACTJOB
exec java -jar "C:/acabes/as400/five250/five250.jar" run-script js_orchestrator_demo "$@"
